filetype plugin indent on
syntax on

set exrc
set guicursor=

set relativenumber
set nu

set nohlsearch
set incsearch

set noerrorbells

set tabstop=4 softtabstop=4
set shiftwidth=4

set expandtab
set smartindent
set nowrap
set noswapfile
set nobackup

set undodir=~/.vim/undodir
set undofile

set scrolloff=8

set hidden
set cmdheight=2

set signcolumn=yes
set colorcolumn=80

set updatetime=50

set shortmess+=c

set laststatus=2
set noshowmode

" TODO(#1): Search for plugin like LiveShare in VSCode 
"  Maybe a good soul made such plugin already, if not, a great project :)

" Plugins
call plug#begin('~/.vim/plugged')
" colorscheme
Plug 'kaicataldo/material.vim', { 'branch': 'main' }

" lightline
Plug 'itchyny/lightline.vim'

" file autoformatter
Plug 'Chiel92/vim-autoformat'

" typescript & .jsx, .tsx syntax
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'

" Git integration
Plug 'airblade/vim-gitgutter'

" Syntax Highlighting
Plug 'sheerun/vim-polyglot'

" Filesystem
Plug 'preservim/nerdtree'
call plug#end()

let mapleader = " "
" mapping autoformat
nnoremap <leader>ff :Autoformat<CR>

" mapping nerdtree
nnoremap <leader>n :NERDTreeToggle<CR>

" mapping movement between splits
nnoremap <leader>sh <C-W><C-h>
nnoremap <leader>sj <C-W><C-j>
nnoremap <leader>sk <C-W><C-k>
nnoremap <leader>sl <C-W><C-l>

" set file .tsx, .jsx to typescriptreact filetype
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
" create autoformatter for typescriptreact filetype
let g:formatters_typescriptreact = ['prettier']

let g:material_theme_style = 'default'
let g:material_terminal_italics = 1
colorscheme material
let g:lightline = { 'colorscheme': 'material_vim' }

