syntax on

set exrc
set guicursor=

set relativenumber
set nu

set nohlsearch
set incsearch

set noerrorbells

set tabstop=4 softtabstop=4
set shiftwidth=4

set expandtab
set smartindent
set nowrap
set noswapfile
set nobackup

set undodir=~/.vim/undodir
set undofile

set scrolloff=8

set hidden
set cmdheight=2

set signcolumn=yes
set colorcolumn=80

set shortmess+=c

" Plugins
call plug#begin('~/.vim/plugged')
" colorscheme
Plug 'gruvbox-community/gruvbox'

" file autoformatter
Plug 'Chiel92/vim-autoformat'

" typescript & .jsx, .tsx syntax
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'

call plug#end()

" autoformat on save
au BufWrite * :Autoformat

" set file .tsx, .jsx to typescriptreact filetype
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescriptreact
" create autoformatter for typescriptreact filetype
let g:formatters_typescriptreact = ['prettier']

set background=dark
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_italic=1
colorscheme gruvbox
